# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  database_url: ${{ secrets.DATABASE_URL }}
  
  cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
  cloudflare_endpoint: ${{ secrets.CLOUDFLARE_ENDPOINT }}
  cloudflare_acessKey: ${{ secrets.CLOUDFLARE_ACESSKEY }}
  cloudflare_secretKey: ${{ secrets.CLOUDFLARE_SECRETKEY }}
  cloudflare_bucket: ${{ secrets.CLOUDFLARE_BUCKET }}
  cloudflare_publicUrl: ${{ secrets.CLOUDFLARE_PUBLICURL }}
  
  google_client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
  google_client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -U

    
    
